### ISSUE TITLE
packagist is not getting updated

### ISSUE THREAD

**Issue by Pezhvak** [snuzi/tiktok-scraper-php#8]
hi, we solved dotenv version in composer.json #7 but i cannot pull it by composer, the package is not auto updated. can you please fix this?

**Comment by snuzi** [comment]
Are you using "dev-master"? Maybe try to remove **composer.lock** and then reinstall packages again.

**Comment by Pezhvak** [comment]
@snuzi yes i tried dev-master before opening the issue, here is the command i am using to pull the repo:
`composer require sabri/tiktok:dev-master`

it can't be fixed by removing the composer.lock since it hasn't been installed yet, it's why i pulled the changes in the first place.

maybe a tag to release a minor version? also please note that packagist is not set to pull updates automatically.

**Comment by snuzi** [comment]
Have you tried to clear composer cache?
A workaround can also be to specify commit ID like `"dev-master#COMMIT_ID_HERE"`
Anyway I have created a new release **v1.0.1**

Please let me know if this worked.

**Comment by Pezhvak** [comment]
![Screen Shot 2020-05-28 at 1 05 02 PM](https://user-images.githubusercontent.com/3134479/83118656-e2b8be80-a0e3-11ea-99c0-3bbe24140ab3.png)

packagist cannot detect the new release, you should either do it manually or enable "pull updates automatically" as i mentioned before.

please take a look at your packagist: https://packagist.org/packages/sabri/tiktok

**Comment by snuzi** [comment]
It should be updated now. Thanks
